Repository prokyhouse/moodTracker, pull requests merged in 2024-10, with the labels that each got.

#3 MT-33: Экран "Статистика"
  MoodTracker/Design/AppResources/AppImages/AppImages.swift
  MoodTracker/Domain/UseCases/Statistics/StatisticsUseCase.swift
  MoodTracker/MoodTracker.xcodeproj/project.pbxproj
  MoodTracker/MoodTracker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MoodTracker/MoodTracker/Application/AppDelegate.swift
  MoodTracker/MoodTracker/Assembly/ServiceAssembly.swift
  MoodTracker/MoodTracker/Assembly/UseCaseAssembly.swift
  MoodTracker/MoodTracker/Presentation/Modules/Main/Presenter/MainPresenter.swift
  MoodTracker/MoodTracker/Presentation/Modules/Main/ViewControllers/MainViewController.swift
  MoodTracker/MoodTracker/Presentation/Modules/Statistics/Assembly/StatisticsAssembly.swift
  MoodTracker/MoodTracker/Presentation/Modules/Statistics/Presenter/StatisticsPresenter.swift
  MoodTracker/MoodTracker/Presentation/Modules/Statistics/StatisticsCoordinator.swift
  MoodTracker/MoodTracker/Presentation/Modules/Statistics/ViewControllers/StatisticsViewController.swift
  MoodTracker/MoodTracker/Presentation/Modules/Statistics/ViewControllers/View/StatisticsDataView.swift
  MoodTracker/MoodTracker/Presentation/Modules/Statistics/ViewControllers/View/StatisticsDataViewModel.swift
  MoodTracker/MoodTracker/Presentation/Modules/TabBar/Coordinators/TabBarCoordinator.swift
  MoodTracker/MoodTracker/Presentation/Modules/TabBar/Models/TabBarPage.swift
  MoodTracker/Storage/Models/MoodNote+CoreDataClass.swift
  MoodTracker/Storage/Models/MoodNote+CoreDataProperties.swift
  MoodTracker/Storage/Models/PersistentContainer.swift
  MoodTracker/Storage/Models/Protocols/ToCoreDataConvertible.swift
  MoodTracker/Storage/Models/Protocols/ToCoreDataStorable.swift
  MoodTracker/Storage/MoodTracker.xcdatamodeld/MoodTracker.xcdatamodel/contents
  MoodTracker/Storage/Services/CoreDataService.swift
  MoodTracker/Storage/Services/CoreDataServiceDelegate.swift
Labels: feature

#5 NO_TICKET: Добавила описание запуска проекта
  GET_STARTED.md
Labels: Tech

#7 MT-43: Дополнил LICENSE
  LICENSE
Labels: documentation

#9 MT-18: Создание компонента Слайдер
  MoodTracker/Design/Reusable/MoodSlider/MoodSlider.swift
Labels: feature

#10 MT-27: Внесение и удаление записи на главной
  MoodTracker/MoodTracker/Presentation/Modules/Main/Assembly/MainAssembly.swift
  MoodTracker/MoodTracker/Presentation/Modules/Main/MainCoordinator.swift
  MoodTracker/MoodTracker/Presentation/Modules/Main/Presenter/MainPresenter.swift
  MoodTracker/MoodTracker/Presentation/Modules/Main/ViewControllers/MainViewController.swift
Labels: feature

#12 MT-20: UI экрана добавления записи
  MoodTracker/Design/AppResources/AppImages/AppImages.swift
  MoodTracker/Design/Reusable/BubbleView/BubbleView.swift
  MoodTracker/MoodTracker/Presentation/Modules/AddReport/ViewControllers/AddReportViewController.swift
Labels: feature

#11 MT-7: Флоу добавление новой записи
  MoodTracker/Design/Reusable/FactCell/FactCell.swift
  MoodTracker/Design/UIFormatters/MoodUIFormatter.swift
  MoodTracker/Domain/Mood/MoodType.swift
  MoodTracker/Domain/UseCases/Main/MainUseCase.swift
  MoodTracker/MoodTracker/Assembly/FormatterAssembly.swift
  MoodTracker/MoodTracker/Assembly/UseCaseAssembly.swift
  MoodTracker/MoodTracker/Presentation/Modules/AddReport/Assembly/AddReportAssembly.swift
  MoodTracker/MoodTracker/Presentation/Modules/AddReport/Presenter/AddReportPresenter.swift
Labels: feature
